ALTER TABLE rag_documents
    ADD COLUMN chunk_count INT NOT NULL DEFAULT 0 COMMENT '切片数量' AFTER knowledge_scope,
    ADD COLUMN extracted_text LONGTEXT NULL COMMENT '入库文本内容' AFTER chunk_count,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
